export const activityTypes = {
    cardio: [
        'running',
        'cycling',
        'swimming',
        'walking',
        'rowing',
        'elliptical',
        'stair_climbing',
        'jumping_rope',
        'other',
    ],
    strength: [
        'weightlifting',
        'bodyweight',
        'resistance_bands',
        'kettlebell',
        'dumbbell',
        'barbell',
        'machine',
        'crossfit',
        'other',
    ],
    flexibility: [
        'yoga',
        'stretching',
        'pilates',
        'tai_chi',
        'foam_rolling',
        'ballet',
        'gymnastics',
        'other',
    ],
    sports: [
        'basketball',
        'soccer',
        'tennis',
        'volleyball',
        'badminton',
        'table_tennis',
        'golf',
        'cricket',
        'baseball',
        'rugby',
        'other',
    ],
    hiit: [
        'tabata',
        'circuit',
        'amrap',
        'emom',
        'metcon',
        'bootcamp',
        'crossfit',
        'other',
    ],
} as const;

export type ActivityCategory = keyof typeof activityTypes;
export type ActivityType = (typeof activityTypes)[ActivityCategory][number];
